# Generated by Django 5.1.1 on 2024-09-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comlete',
            new_name='complete',
        ),
    ]
